### ISSUE TITLE
Instruction help?

### ISSUE THREAD

**Issue by kevinkashou** [tomsky/assemble-middleware-styleguide#1]
It doesn't state what is suppose to be in the styleguide.hbs file? This is what i currently have set up on my assemble block ...

<pre>
        assemble: {
            options: {
                flatten: true,
                expand: true,
                layout: 'templates/layouts/layout.hbs',
                partials: 'templates/partials/**/*.hbs',
                data: 'templates/data/*.json',
                plugins: ['assemble-middleware-styleguide']
            },
            project: {
                files: [{
                    expand: true,
                    cwd: 'templates/pages/',
                    src: '**/*.hbs',
                    dest: 'app/',
                    ext: '.html'
                }]
            },
            styleguide: {
                layout: 'templates/styleguide.hbs',
                src: 'templates/assets/sass/',
                dest: 'styleguide'
            }
        },

</pre>

Am I missing antyhing else? 

Thanks.

**Comment by tomsky** [comment]
styleguide.hbs is the handlebars template used to render the styleguide. 

Two arrays are exposed to assemble and can be used in the template. `styleguide` and `sections`.

Examples:

``` html
<ol>
    {{#each styleguide}}
        <li>{{data.header}}</li>
    {{/each}}
</ol>
```

``` html
{{#each sections}}
    <h1><small>{{reference}}</small> - {{header}}</h1>
    {{{description}}}
    <div>
        {{{markup}}}
    </div>
    <pre>{{markup}}</pre>
    <ul>
        {{#each modifiers}}
            <li>
                <h5>{{name}}</h5>
                <pre>{{{markup}}}</pre>
            </li>
        {{/each}}
    </ul>
{{/each}}
```

**Comment by kevinkashou** [comment]
So I put the handlebars content inside the style guide.hbs file, just confuse why comment out the css if that is not being pulled in the styleguide.hbs file? 

Let me know if I got this correct, the json file of styleguide and sections are the one that is controlling the styleguide.hbs file?

**Comment by tomsky** [comment]
Not quite. First your config is wrong. Should be something like:

``` javascript
assemble: {
    options: {
        flatten: true,
        expand: true,
        layout: 'templates/layouts/layout.hbs',
        partials: 'templates/partials/**/*.hbs',
        data: 'templates/data/*.json',
        plugins: ['assemble-middleware-styleguide'],
        styleguide: {
            layout: 'templates/styleguide.hbs',
            src: 'templates/assets/sass/',
            dest: 'styleguide'
        }
    },
    project: {
        files: [{
            expand: true,
            cwd: 'templates/pages/',
            src: '**/*.hbs',
            dest: 'app/',
            ext: '.html'
        }]
    }
},
```

`assemble-middleware-styleguide` parses [KSS](http://warpspire.com/kss/) is finds in any `.scss` file in  
`templates/assets/sass/`. The data parsed is then available in your template as described above and in the [README](https://github.com/tomsky/assemble-middleware-styleguide/blob/master/README.md). That is all this middleware does. You'll have to have a different task that compiles your sass to scss.

**Comment by kevinkashou** [comment]
So that worked thanks for that! But couple of other questions arises from this ...

1) It generated the file but it pulls in the default layout.hbs along with styleguide.hbs how can I just specify just the styleguide.hbs?

2) The generated files doesn't look clean as far as what it looks like how can get it to look simliar to http://warpspire.com/kss/styleguides/ image? Or is that not the intended purpose? Right now i am getting this 
![screen shot 2015-04-01 at 2 29 48 pm](https://cloud.githubusercontent.com/assets/8713386/6953052/9ac032ce-d87b-11e4-93a9-2de8098ec902.png)

Thanks :)

**Comment by tomsky** [comment]
1) You'll have to dig into the [handlebars.js docs](http://handlebarsjs.com/reference.html).
2) No it does not. The scope of this middleware is simply to parse KSS and expose the data to Assemble.
